name       : python-hkdf
version    : 0.0.3
release    : 1
source     :
    - https://pypi.python.org/packages/c3/be/327e072850db181ce56afd51e26ec7aa5659b18466c709fa5ea2548c935f/hkdf-0.0.3.tar.gz : 622a31c634bc185581530a4b44ffb731ed208acf4614f9c795bdd70e77991dca
license    : BSD-2-Clause
component  : programming.python
summary    : This module implements the HMAC Key Derivation function, defined at http://tools.ietf.org/html/draft-krawczyk-hkdf-01s
description: |
    This module implements the HMAC Key Derivation function, defined at http://tools.ietf.org/html/draft-krawczyk-hkdf-01
setup      : |
    %python3_setup
install    : |
    %python3_install
